# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Deploy Adhoc to Firebase App Distribution"
  lane :deploy_to_firebase do
    if is_ci
      match(
        type: "adhoc",
        app_identifier: "TomosukeOkada.Pokedex.Adhoc",
        readonly: is_ci,

      )
    end
    gym(
      project: Pokedex.xcodeproj,
      scheme: Pokedex,
      configuration: Adhoc,
      export_method: ad-hoc,
    )
    run_firebase_app_distribution()
  end

  private_lane

  private_lane :run_firebase_app_distribution do
    firebase_app_distribution(
      app: ENV["FIREBASE_DIST_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end

  desc "Deploy Release to AppStore Connect"
  lane :"deploy_to_appstore_connect" do
    if is_ci
    end
    gym(
      project: Pokedex.xcodeproj,
      scheme: Pokedex,
      configuration: Release,
      output_name: "Pokedex.ipa",
      export_method: app-store,
    )
    run_testflight()
  end

  private_lane :run_testflight do
    upload_to_testflight(
      username: ENV["APPLE_USER_NAME"],
      app_identifier: "TomosukeOkada.Pokedex",
      ipa: "./Pokedex.ipa",
      team_name: ENV["APPLE_TEAM_NAME"],
      team_id: ENV["APPLE_TEAM_ID"],
      skip_waiting_for_build_processing: true,
    )
  end


  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
