name: Firebase_App_Distiribution

on:
  push:
    branches:
      - develop
      
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
    
    steps:
    - uses: actions/checkout@v2
    
    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version
    
    
    
    # SPMで管理しているライブラリのキャッシュ復元
    - name: Cache SPM packages
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Run Fastlane - Firebase App Distribution
      run: fastlane deploy_to_firebase
      env:
        APPLE_USER_NAME: ${{ secrets.APPLE_USER_NAME }}
        APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        FIREBASE_DIST_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
